2015-08-06 13:12:27,733 INFO  [main] util.VersionInfo: HBase 0.98.12-hadoop1
2015-08-06 13:12:27,735 INFO  [main] util.VersionInfo: Subversion git://aspire/home/apurtell/src/hbase -r bbf8bf4362e858bd9bd0511c9289c31b09b7a927
2015-08-06 13:12:27,735 INFO  [main] util.VersionInfo: Compiled by apurtell on Thu Apr  9 18:55:45 PDT 2015
2015-08-06 13:12:29,746 INFO  [main] zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x2e56c4eb connecting to ZooKeeper ensemble=rs1:2181,master:2181
2015-08-06 13:12:29,823 INFO  [main] zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:host.name=master
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:java.version=1.7.0_79
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-7-openjdk-amd64/jre
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:java.class.path=/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../conf:/usr/lib/tools.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/..:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/activation-1.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/asm-3.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-beanutils-1.7.0.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-beanutils-core-1.8.0.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-cli-1.2.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-codec-1.7.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-collections-3.2.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-configuration-1.6.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-digester-1.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-el-1.0.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-httpclient-3.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-io-2.4.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-lang-2.6.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-logging-1.1.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-math-2.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-net-1.4.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/findbugs-annotations-1.3.9-1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/guava-12.0.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hadoop-core-1.2.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hamcrest-core-1.3.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-annotations-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-checkstyle-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-client-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-common-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-common-0.98.12-hadoop1-tests.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-examples-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-hadoop1-compat-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-hadoop-compat-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-it-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-it-0.98.12-hadoop1-tests.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-prefix-tree-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-protocol-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-rest-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-server-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-server-0.98.12-hadoop1-tests.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-shell-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-testing-util-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-thrift-0.98.12-hadoop1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/high-scale-lib-1.1.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/htrace-core-2.04.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/httpclient-4.1.3.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/httpcore-4.1.3.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jackson-core-asl-1.8.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jackson-jaxrs-1.8.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jackson-mapper-asl-1.8.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jackson-xc-1.8.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jamon-runtime-2.3.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jasper-compiler-5.5.23.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jasper-runtime-5.5.23.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jaxb-api-2.2.2.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jaxb-impl-2.2.3-1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jcodings-1.0.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jersey-client-1.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jersey-core-1.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jersey-json-1.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jersey-server-1.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jettison-1.3.1.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jetty-6.1.26.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jetty-sslengine-6.1.26.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jetty-util-6.1.26.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/joni-2.1.2.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jruby-complete-1.6.8.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jsp-2.1-6.1.14.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jsp-api-2.1-6.1.14.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/jsr305-1.3.9.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/junit-4.11.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/libthrift-0.9.0.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/log4j-1.2.17.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/metrics-core-2.2.0.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/netty-3.6.6.Final.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/protobuf-java-2.5.0.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/servlet-api-2.5-6.1.14.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/slf4j-api-1.6.4.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/slf4j-log4j12-1.6.4.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/xmlenc-0.52.jar:/home/hwb/Documents/hbase-0.98.12-hadoop1/bin/../lib/zookeeper-3.4.6.jar:
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
2015-08-06 13:12:29,824 INFO  [main] zookeeper.ZooKeeper: Client environment:os.name=Linux
2015-08-06 13:12:29,825 INFO  [main] zookeeper.ZooKeeper: Client environment:os.arch=amd64
2015-08-06 13:12:29,825 INFO  [main] zookeeper.ZooKeeper: Client environment:os.version=3.16.0-30-generic
2015-08-06 13:12:29,825 INFO  [main] zookeeper.ZooKeeper: Client environment:user.name=hwb
2015-08-06 13:12:29,825 INFO  [main] zookeeper.ZooKeeper: Client environment:user.home=/home/hwb
2015-08-06 13:12:29,825 INFO  [main] zookeeper.ZooKeeper: Client environment:user.dir=/home/hwb/Documents/hbase-0.98.12-hadoop1
2015-08-06 13:12:29,825 INFO  [main] zookeeper.ZooKeeper: Initiating client connection, connectString=rs1:2181,master:2181 sessionTimeout=90000 watcher=hconnection-0x2e56c4eb0x0, quorum=rs1:2181,master:2181, baseZNode=/hbase
2015-08-06 13:12:29,958 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:29,974 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Socket connection established to master/10.0.2.9:2181, initiating session
2015-08-06 13:12:30,011 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session establishment complete on server master/10.0.2.9:2181, sessionid = 0x4f02b1211c0001, negotiated timeout = 90000
2015-08-06 13:12:30,387 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4f02b1211c0001, likely server has closed socket, closing socket connection and attempting reconnect
2015-08-06 13:12:30,501 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=rs1:2181,master:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
2015-08-06 13:12:30,501 INFO  [main] util.RetryCounter: Sleeping 1000ms before retry #0...
2015-08-06 13:12:30,899 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:30,900 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Socket connection established to rs1/10.0.2.10:2181, initiating session
2015-08-06 13:12:30,907 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session establishment complete on server rs1/10.0.2.10:2181, sessionid = 0x4f02b1211c0001, negotiated timeout = 90000
2015-08-06 13:12:32,258 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4f02b1211c0001, likely server has closed socket, closing socket connection and attempting reconnect
2015-08-06 13:12:32,775 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:33,301 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:33,304 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:33,776 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:34,778 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:35,370 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:35,371 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:35,579 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:35,579 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:35,778 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:36,779 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:37,086 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:37,087 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:37,780 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:37,847 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:37,848 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:38,781 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:39,749 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:39,750 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:39,782 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:40,000 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:40,001 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:40,784 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:41,291 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:41,292 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:41,535 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:41,536 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:41,785 INFO  [main] ipc.Client: Retrying connect to server: master/10.0.2.9:9000. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1 SECONDS)
2015-08-06 13:12:41,788 WARN  [main] util.DynamicClassLoader: Failed to identify the fs of dir hdfs://master:9000/hbase/lib, ignored
java.net.ConnectException: Call to master/10.0.2.9:9000 failed on connection exception: java.net.ConnectException: Connection refused
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:1142)
	at org.apache.hadoop.ipc.Client.call(Client.java:1118)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:229)
	at com.sun.proxy.$Proxy3.getProtocolVersion(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:85)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:62)
	at com.sun.proxy.$Proxy3.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.checkVersion(RPC.java:422)
	at org.apache.hadoop.hdfs.DFSClient.createNamenode(DFSClient.java:183)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:281)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:245)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:100)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1446)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:67)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1464)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:263)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:187)
	at org.apache.hadoop.hbase.util.DynamicClassLoader.<init>(DynamicClassLoader.java:104)
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.<clinit>(ProtobufUtil.java:204)
	at org.apache.hadoop.hbase.ClusterId.parseFrom(ClusterId.java:64)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:69)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:907)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:701)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:457)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:436)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:317)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:194)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:216)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:511)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:481)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:457)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:583)
	at org.apache.hadoop.ipc.Client$Connection.access$2200(Client.java:205)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1249)
	at org.apache.hadoop.ipc.Client.call(Client.java:1093)
	... 39 more
2015-08-06 13:12:42,812 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:42,813 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:42,914 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=rs1:2181,master:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-08-06 13:12:42,914 INFO  [main] util.RetryCounter: Sleeping 1000ms before retry #0...
2015-08-06 13:12:43,352 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:43,352 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:45,285 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:45,286 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:45,387 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=rs1:2181,master:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-08-06 13:12:45,387 INFO  [main] util.RetryCounter: Sleeping 2000ms before retry #1...
2015-08-06 13:12:45,955 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:45,956 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:47,820 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:47,821 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:47,923 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=rs1:2181,master:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-08-06 13:12:47,923 INFO  [main] util.RetryCounter: Sleeping 4000ms before retry #2...
2015-08-06 13:12:48,562 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:48,562 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:49,752 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:49,753 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:50,129 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:50,130 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:51,610 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:51,611 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:52,239 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:52,243 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:52,343 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=rs1:2181,master:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-08-06 13:12:52,343 INFO  [main] util.RetryCounter: Sleeping 8000ms before retry #3...
2015-08-06 13:12:53,616 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:53,617 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:54,484 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:54,484 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:56,072 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:56,073 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:56,908 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:56,909 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:58,714 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:58,715 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:12:59,502 INFO  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Opening socket connection to server master/10.0.2.9:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:12:59,502 WARN  [main-SendThread(master:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:13:01,124 INFO  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Opening socket connection to server rs1/10.0.2.10:2181. Will not attempt to authenticate using SASL (unknown error)
2015-08-06 13:13:01,126 WARN  [main-SendThread(rs1:2181)] zookeeper.ClientCnxn: Session 0x4f02b1211c0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-08-06 13:13:01,228 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=rs1:2181,master:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-08-06 13:13:01,228 ERROR [main] zookeeper.RecoverableZooKeeper: ZooKeeper exists failed after 4 attempts
2015-08-06 13:13:01,228 WARN  [main] zookeeper.ZKUtil: hconnection-0x2e56c4eb-0x4f02b1211c0001, quorum=rs1:2181,master:2181, baseZNode=/hbase Unable to set watcher on znode (/hbase)
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:923)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:597)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1624)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1670)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1724)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1931)
	at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3372)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3399)
	at org.apache.hadoop.hbase.client.HBaseAdmin.shutdown(HBaseAdmin.java:2153)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:228)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
2015-08-06 13:13:01,228 ERROR [main] zookeeper.ZooKeeperWatcher: hconnection-0x2e56c4eb-0x4f02b1211c0001, quorum=rs1:2181,master:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:923)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:597)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1624)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1670)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1724)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1931)
	at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3372)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3399)
	at org.apache.hadoop.hbase.client.HBaseAdmin.shutdown(HBaseAdmin.java:2153)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:228)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
2015-08-06 13:13:01,228 ERROR [main] client.HConnectionManager$HConnectionImplementation: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
2015-08-06 13:13:01,229 INFO  [main] client.HConnectionManager$HConnectionImplementation: getMaster attempt 1 of 1 failed; no more retrying.
org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:934)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:597)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1624)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1670)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1724)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1931)
	at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3372)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3399)
	at org.apache.hadoop.hbase.client.HBaseAdmin.shutdown(HBaseAdmin.java:2153)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:228)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:923)
	... 15 more
2015-08-06 13:13:01,240 ERROR [main] master.HMasterCommandLine: Failed to stop master
org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=1, exceptions:
Thu Aug 06 13:13:01 CEST 2015, org.apache.hadoop.hbase.client.RpcRetryingCaller@71172e7a, org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase

	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:131)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3399)
	at org.apache.hadoop.hbase.client.HBaseAdmin.shutdown(HBaseAdmin.java:2153)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:228)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1698)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1724)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1931)
	at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3372)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
	... 8 more
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:934)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:597)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1624)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1670)
	... 12 more
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:923)
	... 15 more
